spring.application.name=fundoo-api-gateway

server.port=8080

# =========================================================
# EUREKA CLIENT
# =========================================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true


# =========================================================
# GATEWAY ROUTES
# =========================================================

# -------------------------
# AUTH SERVICE
# -------------------------

spring.cloud.gateway.server.webflux.routes[0].id=fundoo-auth-service

spring.cloud.gateway.server.webflux.routes[0].uri=lb://FUNDOO-AUTH-SERVICE

spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**


# -------------------------
# NOTES SERVICE
# -------------------------

spring.cloud.gateway.server.webflux.routes[1].id=fundoo-notes-service

spring.cloud.gateway.server.webflux.routes[1].uri=lb://FUNDOO-NOTES-SERVICE

spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/notes/**,/api/tags/**


# -------------------------
# NOTIFICATION SERVICE
# -------------------------

spring.cloud.gateway.server.webflux.routes[2].id=fundoo-notification-service

spring.cloud.gateway.server.webflux.routes[2].uri=lb://FUNDOO-NOTIFICATION-SERVICE

spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/notifications/**


# =========================================================
# JWT
# =========================================================

jwt.secret=my-secret-key-for-fundoo-notes-application-123456789

jwt.expiration=86400000


# =========================================================
# REDIS
# =========================================================

spring.data.redis.host=localhost
spring.data.redis.port=6379


# =========================================================
# ACTUATOR
# =========================================================

management.endpoints.web.exposure.include=health,info,metrics,gateway

management.endpoint.health.show-details=always


# =========================================================
# SPRING BOOT ADMIN
# =========================================================

spring.boot.admin.client.url=http://localhost:9090